### ISSUE TITLE
problems with german umlauts

### ISSUE THREAD

**Issue by MirkoBrunner** [streetsidesoftware/vscode-cspell-dict-extensions#73] opened 2021-04-15 15:33 UTC
Words with German umlauts are not correctly recognized by the extension. As you can see in the picture below.

<img width="724" alt="Bildschirmfoto 2021-04-15 um 17 29 33" src="https://user-images.githubusercontent.com/1172356/114896419-9caa3d80-9e10-11eb-8716-93a816fee66f.png">

**Comment by Jason3S** [comment] 2021-05-01 18:54
@MirkoBrunner,

Thank you for reporting the issue.

I'm not able to reproduce it. Would you please attach a sample file?

![image](https://user-images.githubusercontent.com/3740137/116792173-5109bc00-aabf-11eb-8934-71cf06e700b6.png)

Does it happen in all types of files or just `.html`?

**Comment by Jason3S** [comment] 2021-05-01 18:56
Here is the text I used to test with:

```
# Der Nordseekanal

Der Nordseekanal (niederländisch Noordzeekanaal) ist ein 21 Kilometer langer Kanal für Seeschiffe in den Niederlanden. Er verbindet in der Provinz Nordholland den Hafen von Amsterdam in westlicher Richtung mit der Nordsee bei IJmuiden.
[1] Hinter dem Seehafen von Amsterdam geht der Kanal in das Binnen-IJ über, das über sieben Kilometer bis nach Schellingwoude an das Markermeer nordöstlich von Amsterdam reicht. 
Für Binnenschiffe steht das Binnen-IJ in direkter Verbindung zum Amsterdam-Rhein-Kanal, der nach 72 Kilometern bei Tiel die Waal und damit das Flussgebiet des Rheins erreicht. 
Um den Wasserstand im Kanalsystem bei 40 Zentimeter unter NAP (NAP = Normaal Amsterdam Peil) zu halten, sind an allen Enden des Systems Schleusen angeordnet. 
Verantwortlich für den Betrieb und die Unterhaltung des gesamten Kanals ist Rijkswaterstaat, die ausführende Behörde des niederländischen Ministeriums für Infrastruktur und Umwelt zum Bau und Unterhalt von Straßen und Wasserwegen.

ausführender   ausfü hrender

<!---  
cspell:words Noordzeekanaal Schellingwoude Rijkswaterstaat Tiel IJmuiden
--->
```

**Comment by Jason3S** [comment] 2021-09-16 21:09
This should be fixed with the latest release of the spell checker.
The issue had to do with how the accent was added to the U.

**Closed by Jason3S** 2021-09-16 21:09 UTC
Labels: Done
